---
- include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: Create dns directory
  file:
    path: "/home/{{ ansible_user }}/dns"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Create named.conf.local for bind
  template:
    src: named.conf.local.j2
    dest: "/home/{{ ansible_user }}/dns/named.conf.local"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Create named.conf.options for bind
  template:
    src: named.conf.options.j2
    dest: "/home/{{ ansible_user }}/dns/named.conf.options"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Create domain zone file for bind
  template:
    src: db.domain.com.j2
    dest: "/home/{{ ansible_user }}/dns/db.{{ domain }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644


- name: Pull the latest bind image
  docker_image:
    name: "{{ bind_image }}"
    source: pull

- name: Ensure no previous dns containers are running
  docker_container:
    name: dns
    state: absent

- name: Bring up the dns container
  docker_container:
    name: "{{ bind_container_name }}"
    image: "{{ bind_image }}"
    state: started
    restart_policy: always
    volumes:
      - /home/{{ ansible_user }}/dns/named.conf.local:/etc/bind/named.conf.local
      - /home/{{ ansible_user }}/dns/named.conf.options:/etc/bind/named.conf.options
      - /home/{{ ansible_user }}/dns/db.{{ domain }}:/etc/bind/db.{{ domain }}
    published_ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "953/tcp"
    networks:
      - name: "{{ backend_docker_network }}"