---
- name: Print information about the target host
  debug:
    msg: 
      - "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
      - "OS Family: {{ ansible_os_family }}"
      - "Architecture: {{ ansible_architecture }}"
      - "Hostname: {{ ansible_hostname }}"
      - "IP Addresses: {{ ansible_all_ipv4_addresses }}"
      - "CPU Cores: {{ ansible_processor_cores }}"
      - "Memory: {{ ansible_memtotal_mb }} MB"


- name: Install common packages on Debian
  apt:
    name:
    - nano
    - curl
    - wget
    - unzip
    - pip
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'