---
- name: Install Docker on Debian
  import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker on Windows
  import_tasks: windows.yml
  when: ansible_os_family == 'Windows'
