---
- include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'


- name: Install Docker packages
  package: 
    name: "{{ docker_packages }}"
    state: "{{ docker_packages_state }}"
  notify: restart docker

- name: Install docker-compose
  package:
    name: "{{ docker_compose_package }}"
    state: "{{ docker_compose_package_state }}"
  notify: restart docker

- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  notify: restart docker

- name: Ensure docker is running and enabled
  service:
    name: docker
    state: started
    enabled: yes

- name: Create backend network
  docker_network:
    name: "{{ backend_docker_network }}"
    state: present

- name: Create frontend network
  docker_network:
    name: "{{ frontend_docker_network }}"
    state: present
