---
- include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: Copy src files
  copy:
    src: files/html
    dest: "{{ php_apache_src_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755


- name: Create the docker-compose.yml file
  template:
    src: docker-compose.yml.j2
    dest: /home/{{ ansible_user }}/web/docker-compose.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Ensure no webserver containers are running
  docker_compose:
    project_src: /home/{{ ansible_user }}/web
    state: absent

- name: Bring up the webserver containers
  docker_compose:
    project_src: /home/{{ ansible_user }}/web
    state: present
    build: yes