---
- name: Create dhcp directory
  file:
    path: "/home/{{ ansible_user }}/dhcp"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Create the dhcpd.conf file
  template:
    src: dhcpd.conf.j2
    dest: /home/{{ ansible_user }}/dhcp/dhcpd.conf
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Create the docker-compose.yml file
  template:
    src: docker-compose.yml.j2
    dest: /home/{{ ansible_user }}/dhcp/docker-compose.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Ensure no previous dhcp containers are running
  docker_compose:
    project_src: /home/{{ ansible_user }}/dhcp
    state: absent

- name: Bring up the dhcp containers
  docker_compose:
    project_src: /home/{{ ansible_user }}/dhcp
    state: present
    build: yes