---

- name: Create a node_exporter directory
  file:
    path: /home/{{ ansible_user }}/node_exporter
    state: directory
    mode: 0755

- name: Create installation script form template
  template:
    src: install.sh.j2
    dest: /home/{{ ansible_user }}/node_exporter/install.sh
    mode: 0755

- name: Install and run node_exporter
  shell: /home/{{ ansible_user }}/node_exporter/install.sh
  args:
    chdir: /home/{{ ansible_user }}/node_exporter/
