---
- name: Create db directory
  file:
    path: "/home/{{ ansible_user }}/db"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Copy init.sql file
  copy:
    src: init.sql
    dest: /home/{{ ansible_user }}/db/init.sql
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Create the docker-compose.yml file
  template:
    src: docker-compose.yml.j2
    dest: /home/{{ ansible_user }}/db/docker-compose.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Ensure no previous db containers are running
  docker_compose:
    project_src: /home/{{ ansible_user }}/db
    state: absent

- name: Bring up the db containers
  docker_compose:
    project_src: /home/{{ ansible_user }}/db
    state: present
    build: yes