---
- name: Provision the docker host
  hosts: LS-01
  become: yes
  roles:
    - common
    - docker
    - db
    - webserver
    - glpi
    - node_exporter
    - monitoring
    - dhcp

# - name: Provision the second docker host
#   hosts: LS-02
#   become: yes
#   roles:
#     - common
#     - docker
#     - node_exporter