version: '3'
services:
  apache:
    build: ./apache
    networks:
      - frontend
      - backend
    ports:
      - 80:80
    volumes:
      - ./html/:/var/www/html
    depends_on:
      - php
  php:
    image: php:7.2-fpm-alpine
    networks:
      - backend
    volumes:
      - ./html/:/var/www/html/
  db:
    image: mariadb:10.3
    networks:
      - backend
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root?2023
      MARIADB_DATABASE: UAN
      MARIADB_USER: dbuser
      MARIADB_PASSWORD: dbuser?2023
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - backend
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root?2023
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser?2023
      MYSQL_DATABASE: UAN

networks:
  frontend:
  backend: